In [1]:
%pip install numpy 
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [2]:
big_list = list(range(1000000)) 
big_array = np.arange(1000000)

In [3]:
%timeit [x **2 for x in big_list]

159 ms ± 4.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit big_array ** 2

4.19 ms ± 327 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
### Creating arrays

In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]]) # 2-d array 
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
a = np.array([0,0,0,0]) 
print(a)

[0 0 0 0]


In [9]:
zero = np.zeros((2,3)) 
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [12]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
rng = np.random.default_rng(seed=42) 
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [15]:
print(rng.integers(1,10,size=(3,3))) # uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [16]:
print(rng.normal(loc=0,scale=1,size=5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


In [17]:
### array attributes and data types

In [18]:
M = np.array ([[1,2,3],[4,5,6]])
print(M)
print(M.ndim)   # Number of dimensions 
print(M.shape)  # Shape of the array
print(M.size)
print(M.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [19]:
ints = np.array([1,2,3], dtype=np.int32)

In [20]:
ints.dtype

dtype('int32')

In [21]:
floats = np.array([1,2,3],dtype = np.float64) 
floats.dtype

dtype('float64')

In [22]:
## indexing and slicing

In [23]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
print(x[0])

10


In [25]:
print(x[5])

15


In [26]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
print(M[1,2])

7


In [28]:
M[1]

array([5, 6, 7, 8])

In [29]:
print(M[:,1])

[ 2  6 10]


In [31]:
print(M[:,0])

[1 5 9]


In [32]:
# Vector Operation

In [33]:
a  = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a)

[1 2 3 4]


In [35]:
print(b)

[10 20 30 40]


In [36]:
print(a+b)

[11 22 33 44]


In [37]:
print(a*b)

[ 10  40  90 160]


In [38]:
# Broadcasting

In [39]:
a = np.array([1,2,3])
b = 10

In [40]:
print(a+b)

[11 12 13]


In [43]:
a = np.array([[1,2,3],
              [4,5,6]])
a.shape

(2, 3)

In [44]:
b = np.array([10,20,30])
b.shape

(3,)

In [45]:
print(a+b)

[[11 22 33]
 [14 25 36]]
